stages:
  - start
  - deploy
  - finish

notify_start:
  stage: start
  tags:
    - dev-shell-runner
  script:
    - |
      telegram-send "⚙️ Service deployment started...
      Project: $CI_PROJECT_NAME
      Branch: $CI_COMMIT_BRANCH
      User: $CI_COMMIT_AUTHOR
      Message: $CI_COMMIT_MESSAGE"

deploy:
  stage: deploy
  tags:
    - dev-shell-runner
  script:
    - docker-compose up -d --build --force-recreate --remove-orphans

notify_success:
  stage: finish
  tags:
    - dev-shell-runner
  script:
    - telegram-send "✅ Service successfully deployed."

notify_error:
  stage: finish
  tags:
    - dev-shell-runner
  script:
    - |
      telegram-send "❌ Service fucked up.
      Pipeline: $CI_PIPELINE_URL
      Job: $CI_JOB_URL"
  when: on_failure