variables:
  GIT_CLEAN_FLAGS: none

stages:
  - start
  - deploy
  - finish

notify_start:
  stage: start
  tags:
    - dev-shell-runner
  script:
    - telegram-send "Web service deployment started...
    - Branch: $CI_COMMIT_BRANCH
    - User: $CI_COMMIT_AUTHOR
    - Message: $CI_COMMIT_MESSAGE
    - "

deploy:
  stage: deploy
  tags:
    - dev-shell-runner
  script:
    - docker-compose up -d --build

notify_success:
  stage: finish
  tags:
    - dev-shell-runner
  script:
    - telegram-send "✅ Web service successfully deployed."

notify_error:
  stage: finish
  tags:
    - dev-shell-runner
  script:
    - telegram-send "❌ Web service fucked up."
  when: on_failure