variables:
  CI_CD_UTILS_PATH: "/home/ci-cd-utils"

stages:
  - start
  - deploy
  - finish

notify_start:
  stage: start
  tags:
    - dev-shell-runner
  script:
    - $CI_CD_UTILS_PATH/notifications/deployment-start.sh

deploy:
  stage: deploy
  tags:
    - dev-shell-runner
  script:
    - docker-compose up -d --build --force-recreate --remove-orphans

notify_success:
  stage: finish
  tags:
    - dev-shell-runner
  script:
    - $CI_CD_UTILS_PATH/notifications/deployment-success.sh

notify_error:
  stage: finish
  tags:
    - dev-shell-runner
  script:
    - $CI_CD_UTILS_PATH/notifications/deployment-fail.sh
  when: on_failure