stages:
  - deploy
  - notify

notify_start:
  stage: notify
  tags:
    - dev-shell-runner
  script:
    - telegram-send "Web service deployment started..."

deploy:
  stage: deploy
  tags:
    - dev-shell-runner
  script:
    - docker-compose up -d --build

notify_success:
  stage: notify
  tags:
    - dev-shell-runner
  script:
    - telegram-send "Web service successfully deployed."

notify_error:
  stage: notify
  tags:
    - dev-shell-runner
  script:
    - telegram-send "Web service fucked up."
  when: on_failure