variables:
  ROOT_PATH: "/home/admin/korea-bus/api"

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - cd $ROOT_PATH
    - docker-compose down
    - git pull origin master
    - docker-compose up -d