variables:
  ROOT_PATH: "/home/admin/korea-bus/web"

stages:
  - deploy

before_script:
  - echo "Current branch -" $CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - cd $ROOT_PATH
    - docker-compose down
    - git pull origin master
    - docker-compose up -d