apiVersion: apps/v1
kind: Deployment
metadata:
  name: korea-bus-web
  labels:
    app: korea-bus-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: korea-bus-web
  template:
    metadata:
      labels:
        app: korea-bus-web
    spec:
      containers:
      - name: korea-bus-web
        image: korea-bus-web
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
 
apiVersion: v1
kind: Service
metadata:
  name: korea-bus-web
  labels:
    app: korea-bus-web
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: korea-bus-web